In [2]:
!pip3 install numpy

In [4]:
import numpy as np

In [10]:
my_lst=[1,2,3,4,5]
my_lst

[1, 2, 3, 4, 5]

In [11]:
arr=np.array(my_lst)
print(arr)

[1 2 3 4 5]


In [13]:
type(arr)

numpy.ndarray

In [15]:
arr.shape

(5,)

# converting one dimentional array to multi dimentional array

In [17]:
myarray1=[1,2,3,4,5]
myarray2=[2,3,4,5,6]
myarray3=[3,4,5,6,7]

In [20]:
arr=np.array([myarray1,myarray2,myarray3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [22]:
arr.shape

(3, 5)

Reshaping the array (number of elements from the current array to reshaping array must be equal)

In [24]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [26]:
arr.shape

(3, 5)

In [27]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7]])

The above array is 2 dimentional

# Indexing

In [67]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [68]:
arr[3]

4

In [69]:
arr[3:]=100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [51]:
arr=arr.reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Selecting all rows and column's elements

In [52]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Selecting first two rows

In [56]:
arr[0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

selecting first two rows and two columns

In [58]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

Selecting row two to three and column two to three

In [59]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

# Random Array generation

In [61]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array generation with step

In [63]:
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

generation of array from one range to another

In [70]:
arr=np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [72]:
arr1=arr

In [74]:
arr1[3:]=500
arr1

array([  1.        ,   1.18367347,   1.36734694, 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        ])

In [76]:
arr

array([  1.        ,   1.18367347,   1.36734694, 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        , 500.        , 500.        ,
       500.        , 500.        ])

In [80]:
arr=np.linspace(1,10,50)
arr

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [81]:
val=2
arr<2

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [83]:
arr[arr<5]

array([1.        , 1.18367347, 1.36734694, 1.55102041, 1.73469388,
       1.91836735, 2.10204082, 2.28571429, 2.46938776, 2.65306122,
       2.83673469, 3.02040816, 3.20408163, 3.3877551 , 3.57142857,
       3.75510204, 3.93877551, 4.12244898, 4.30612245, 4.48979592,
       4.67346939, 4.85714286])

In [85]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [90]:
np.arange(0,20,2).reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [92]:
a1=np.arange(0,10).reshape(5,2)
a2=np.arange(0,20,2).reshape(5,2)
a1*a2

array([[  0,   2],
       [  8,  18],
       [ 32,  50],
       [ 72,  98],
       [128, 162]])

In [94]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [96]:
np.ones(10).reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [98]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

by default is float data types

In [100]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Random generation of array

In [109]:
arr=np.random.rand(10)
arr

array([0.84168841, 0.82584217, 0.63333531, 0.61028744, 0.83261495,
       0.49011967, 0.14835253, 0.04154789, 0.74775758, 0.95372118])

In [107]:
arr=np.random.rand(4,4)
arr

array([[0.06062111, 0.40240339, 0.20448573, 0.04522725],
       [0.49455595, 0.74762071, 0.75853959, 0.7440518 ],
       [0.48363512, 0.10207896, 0.34931665, 0.63649523],
       [0.6377925 , 0.04695355, 0.37831369, 0.75633539]])

In [110]:
arr=np.random.rand(4,4)*100
arr

array([[ 7.26955506, 78.7603649 , 71.30423   , 71.27721271],
       [31.72716953, 31.77689231, 78.01426   , 30.02538582],
       [10.37201481, 36.93240415,  2.60306373, 83.89123281],
       [85.00813306, 28.47916603,  8.68385385, 14.03238515]])

Selection random integer from one range to another with number of choices

In [115]:
np.random.randint(0,100,8)

array([11, 58, 48, 82, 32, 54, 59, 49])

In [118]:
np.random.randint(0,100,25)

array([74, 55, 43, 69, 36, 96, 50, 12, 14, 44, 42, 11, 23,  8, 46,  0, 94,
       97, 61, 82, 44, 97, 22, 22, 95])